### ISSUE TITLE
hasManyThrough examples?

### ISSUE THREAD

**Issue by jjwilliams** [strongloop/loopback-example-relations#22] opened 2015-12-16 20:54 UTC
I'm having a difficult time understanding hasManyThrough (and I do not see any examples here). I understand conceptually, its a many to many with an intervening model, which may or may not have an additional payload of data (typically it should otherwise there is no point for hasManyThrough).

But in practice, I've tried to model a simple User > Bid > Auction using this, and the results returned are confusing. An Auction can have many users bid on it, and a user can have many auctions that they bid on. This makes sense to use Bid as an intervening model (with the amount being stored on Bid). But the implementation of it feels clunky.

When modeled through LoopBack, /Auctions/{id}/bids gives a list of users, with no actual amount (bid.amount is the additional payload data in the Bid model - but doesn't get returned in the call?). Am I missing something here? Can you show any examples of hasManyThrough? I've resorted to using belongsTo with hasMany for now.

**Comment by jannyHou** [comment] 2015-12-18 21:18
hey @jjwilliams thanks for your suggestion and i m very glad to help you to solve your concerns!
I guess you already read our document page [`hasManyThrough`](https://docs.strongloop.com/display/public/LB/HasManyThrough+relations), it has a detailed introduction of how to establish the relation.

I created a [new branch](https://github.com/strongloop/loopback-example-relations/tree/feature/has-many-through) in this repo for hasManyThrough relation demo, implemented the example of Patient > Appointment > Physician from document I mentioned above.

You can run the example from that branch and get a deep understanding of `hasManyThrough` by going to "http://localhost:3000/explorer"
When check "additional payload data" in the intervening model, you could use api `GET /Appointments`, and use filter `{"where": {"physicianId": yourid}}`.
Which in your case should be `GET /Bids` with filter `{"where": {"auctionId": yourid}}`

I will see if I can publish this demo in the future. I hope it gives you a clearer idea about `hasManyThrough` and your feedback are welcomed!

**Comment by jjwilliams** [comment] 2015-12-19 03:40
So I guess it really comes down to preference of how you like to access your data. I prefer /Patient/1/Appointments, so I will stick to the belongsTo and hasMany method. Thank you for your example! I thought I was doing it wrong, turns out I was just accessing it incorrectly.

**Comment by jannyHou** [comment] 2015-12-21 18:17
@jjwilliams thanks! Since the demo is ready in branch, I am closing this issue here. Feel free to reopen it if you have any further questions.

**Closed as completed by jannyHou** 2015-12-21 18:17 UTC

**Comment by xieyang784** [comment] 2016-10-25 09:51
Hi @jannyHou, I want to know is there a example for Self through? Thanks. I follow this page but didn't work yet. Looking forward your reply. [http://loopback.io/doc/en/lb2/HasManyThrough-relations.html#self-through](http://loopback.io/doc/en/lb2/HasManyThrough-relations.html#self-through)

**Comment by jannyHou** [comment] 2016-10-25 14:28
@xieyang784 Thanks for your feedback, good idea, I will add a self through example asap. 

Could you elaborate more about what didn't work? eg: some api returns error?
We are using model `User` to do the `self through` in doc while `User` has lots of ACLs which may result in 401 authentication errors, etc...

btw, please note that the Upper/Lower case of letter sometimes also affect your app, see bug https://github.com/strongloop/loopback-datasource-juggler/issues/1003#issuecomment-244451536

I am glad to discuss with you here and appreciate it if you can fork the sandbox https://github.com/strongloop/loopback-sandbox and replace with your code, then add some steps of how to reproduce your error.
