### ISSUE TITLE
loopback-example-relations refers to missing file

### ISSUE THREAD

**Issue by socrates58** [strongloop/loopback-example-relations#23] opened 2016-01-02 20:55 UTC
https://github.com/strongloop/loopback-example-relations refers to sample-orders.js. The link is broken, and it's not in loopback-example-relations/server/boot

**Comment by jannyHou** [comment] 2016-01-05 20:17
@socrates58 Thank you! this is an error caused by code refactor. It's fixed now!

**Closed as completed by jannyHou** 2016-01-05 20:17 UTC
Labels: bug
