### ISSUE TITLE
EmbedsOne producing error

### ISSUE THREAD

**Issue by essaji** [strongloop/loopback-example-relations#29] opened 2016-03-13 11:03 UTC
I have following two models

> Nurse
> Room

A room has belongsTo relation with the nurse model as defined below:

```
"relations": {
        "nurse": {
            "model": "Nurse",
            "type": "belongsTo",
            "foreignKey": "nid"
        }
    }
```

which works fine and produces the data on following urls

> http://localhost:3000/api/Rooms/1
> http://localhost:3000/api/Rooms/1/nurse

but when I try the embedsOne relation as defined below:

```
"relations": {
        "nurse": {
            "model": "Nurse",
            "type": "embedsOne",
            "foreignKey": "nid"
        }
    }
```

and try accessing url at 

> http://localhost:3000/api/Rooms/1

 I get the following error:

> message: "ER_BAD_FIELD_ERROR: Unknown column '_nurse' in 'field list'",

thoughts?

**Comment by jannyHou** [comment] 2016-03-23 19:48
@essaji I am trying to reproduce your issue, will post my result later, but for a better debugging, could you fork this sandbox then upload your code? https://github.com/strongloop/loopback-sandbox
thanks a lot!

---

I tried and embedsOne works fine for me:
Could you check [definition of embedsOne relation](https://github.com/strongloop/loopback-example-relations/blob/master/common/models/customer.json#L14-L22),
and also how to [create model instance through relation](https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/z-customer-address.js#L11) in this repo?
Please upload your sandbox if you still run into issues:)

**Comment by jannyHou** [comment] 2016-04-25 14:54
@essaji do you still run into this issue? any update?

**Comment by essaji** [comment] 2016-04-25 15:44
Yes, I am still running into this issue. The data is to be embedded is not coming from the memory instead the data is being retrieved from the Mysql database.

**Comment by jannyHou** [comment] 2016-04-25 15:50
@essaji For mysql, I think you need to auto-migrate your model first: please check https://docs.strongloop.com/display/LB/Creating+a+database+schema+from+models#Creatingadatabaseschemafrommodels-Auto-migrate to see details.
If it still cannot solve your problem, could you provide me your code with the sandbox I mentioned in https://github.com/strongloop/loopback-example-relations/issues/29#issuecomment-200516141?

**Comment by jannyHou** [comment] 2016-08-18 17:44
@essaji can you try with 

```
"relations": {
        "nurse": {
            "model": "Nurse",
            "type": "embedsOne",
            "property": "nid"
        }
    }
```

?
In embeds relations, you need to set `property` instead of `foreignKey`

**Comment by jannyHou** [comment] 2016-09-20 14:42
I am closing this issue since I could not reproduce it. Please feel free to reopen it if someone could upload the problem code in sandbox. Thanks for understanding :)

**Closed as completed by jannyHou** 2016-09-20 14:42 UTC
