### ISSUE TITLE
Figure out why PR is causing CI tests to fail

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-relations#13] opened 2015-10-20 23:27 UTC
https://github.com/strongloop/loopback-example-relations/pull/10 implements changes to update app per https://github.com/strongloop-internal/scrum-loopback/issues/495, but tests are failing.   There were similar failures in https://github.com/strongloop/loopback-example-access-control/pull/63, but I fixed those.  The same fix did not work here and I am stumped.

**Comment by superkhau** [comment] 2015-11-02 22:31
@crandmck Those changes are incompatible with the project. I believe the updates are breaking things (ie. not backwards compatible). You can prove it by scaffolding a new project and just copying the models and boot scripts over.

**Comment by crandmck** [comment] 2015-11-14 00:52
@jannyHou I assigned this to you because you are listed as the "expert" for this repo in https://github.com/strongloop/loopback-triage/wiki/Repo-experts.  As Simon notes, my attempt to upgrade this app to the latest LB scaffolding didn't work.  Perhaps you can figure out why.

**Comment by jannyHou** [comment] 2015-11-16 14:27
@crandmck  ok, no problem, let me find out the reason.

**Comment by jannyHou** [comment] 2015-11-23 22:26
hey @crandmck @superkhau , the problem is raised with routing set, this snippet

```
app.use('/', function(req, res, next) {
    ...
}
```

should be set as:

```
var router = app.loopback.Router();
router.get('/', function(req, res, next) {
    app.models.Customer.findOne({where: {name: 'Customer A'}}, function(err, customer) {
     if (err) return next(err);
     res.render('index', {customer: customer});
   });
}); 
app.use(router);
```

I merged the two similar repos and uploaded the new project to branch `upgrade-lb-explorer`. Now it's compatible with `loopback-component-explorer`. I plan to add some test cases and write a new README file this week.
Thanks!

**Comment by crandmck** [comment] 2015-11-24 00:56
Awesome!  Let me know when you want me to review and close this.

**Comment by superkhau** [comment] 2015-11-24 22:48
@crandmck Can you review this? Assigning to you.

**Comment by jannyHou** [comment] 2015-12-01 21:24
hey @crandmck  @superkhau  I think the problem is solved, the snippet I mentioned above is one reason(fixed and pr https://github.com/strongloop/loopback-example-relations/pull/20 merged).
The other error is probably raised by missing dependency in `package.json`, in my case, it's `async`.

**Comment by superkhau** [comment] 2015-12-02 00:48
@jannyHou :+1: Merge it!

**Comment by crandmck** [comment] 2015-12-02 23:17
It looks like all these changes have been made.  Can we close this issue now?

**Comment by jannyHou** [comment] 2015-12-03 13:25
Thank you @crandmck ,yeah I think we can close it because new pr has merged.

**Closed as completed** 2015-12-03 21:49 UTC
Labels: bug
